# Site settings
title: Jeric Dy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jericdy.com" # the base hostname & protocol for your site [will turn into http://localhost:4000 when using jekyll serve, see: https://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/#siteurl-is-set-by-the-development-server]
production_url: "http://www.jericdy.com"
timezone: UTC

debug: true

# plugin configs
mini_magick:
  blog-thumbnail-100x:
    source: images/blog
    destination: images/blog/thumbnails/100x
    resize: "100x"
  blog-thumbnail-800x600:
    source: images/blog
    destination: images/blog/thumbnails/800x600
    resize: "800x600"
  games-graphix-thumbnail-x150:
    source: images/games/graphix
    destination: images/games/graphix/thumbnails/x150
    resize: "x150"
  games-rockmandashfangame-thumbnail-100x:
    source: images/games/rockmandashfangame
    destination: images/games/rockmandashfangame/thumbnails/100x
    resize: "100x"
  games-rockmandashfangame-thumbnail-x150:
    source: images/games/rockmandashfangame
    destination: images/games/rockmandashfangame/thumbnails/x150
    resize: "x150"
  games-rockmandashfangame-thumbnail-400x300:
    source: images/games/rockmandashfangame
    destination: images/games/rockmandashfangame/thumbnails/400x300
    resize: "400x300"
  games-rockmandashfangame-thumbnail-800x600:
    source: images/games/rockmandashfangame
    destination: images/games/rockmandashfangame/thumbnails/800x600
    resize: "800x600"
  games-sworld-thumbnail-x150:
    source: images/games/sworld
    destination: images/games/sworld/thumbnails/x150
    resize: "x150"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
